### ISSUE TITLE
What goes in configuration props?

### ISSUE THREAD

**Issue by praneybehl** [3stack-software/meteor-react-datetimepicker#1]
Thanks for creating the package.
Just can't figure what does the configuration='configurationName' props refer to?
Would you be able to shed some light on it? Maybe point to an example in the docs or something will be highly appreciated.

Thanks in advance.

**Comment by nathan-muir** [comment]
Hey, don't have much documentation available.

`configuration` is an optional feature - you can create named configurations like:

```js
DatetimePicker. configure('shortDateFormat', {
  format: 'xyz'
})
```

then use `configuration='shortDateFormat'` instead of passing the format manually to each instance.
