### ISSUE TITLE
TypeError: React.findDOMNode is not a function

### ISSUE THREAD

**Issue by aminecmi** [3stack-software/meteor-react-datetimepicker#2]
Hello,

In newer versions of react, `React.findDOMNode` is not a function anymore.
It needs to be replaced by `ReactDOM.findDOMNode`

**Comment by egarza54** [comment]
Any updates if this issue will be resolved?

**Comment by nathan-muir** [comment]
@egarza54 it is resolved if you update to 4.14.30_4
